openapi: 3.0.0

info:
  title: Anypoint MQ specfication
  description: Anypoint MQ API specification
  version: 1.0.0

servers:
  - url: https://anypoint.mulesoft.com/mq/admin/api/v1/
    description: Anypoint Cloudhub 
  - url: https://eu1.anypoint.mulesoft.com/mq/admin/api/v1/
    description: Anypoint Cloudhub EU
  - url: https://gov.anypoint.mulesoft.com/mq/admin/api/v1/
    description: Anypoint Cloudhub GOV

security:
  - bearerAuth: [] 
      
paths:
  /organizations/{orgId}/environments/{envId}/regions/{regionId}/destinations:
    parameters:
      - in: path
        name: orgId
        description: The organization Id
        required: true
        schema:
          type: string
      - in: path
        name: envId
        description: The environment id
        required: true
        schema:
          type: string
      - in: path
        name: regionId
        description: The region id for MQ
        required: true
        schema:
          type: string
    get:
      description: Get a list of queues in a region
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':
          $ref: '#/components/responses/SuccessGetQueues'
  /organizations/{orgId}/environments/{envId}/regions/{regionId}/destinations/queues/{queueId}:
    parameters:
      - in: path
        name: orgId
        description: The organization Id
        required: true
        schema:
          type: string
      - in: path
        name: envId
        description: The environment id
        required: true
        schema:
          type: string
      - in: path
        name: regionId
        description: The region id
        required: true
        schema:
          type: string
      - in: path
        name: queueId
        description: The id of a specific queue
        required: true
        schema:
          type: string
    
    get:
      description: Get details about a queue
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':
          $ref: '#/components/responses/SuccessGetQueue'
    patch:
      description: Modify a queue's properties
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFound'
        '200':
          $ref: '#/components/responses/SuccessGetQueue'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/queueBody'
    put:
      description: Create queue
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':
          $ref: '#/components/responses/SuccessGetQueue'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/queueBody'
    delete:
      description: Delete queue 
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '204':
          $ref: '#/components/responses/SuccessDeleteQueue'

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    BadRequestError:
      description: Bad request response
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                title: the response status code 
                default: 400
              message:
                type: string
                title: the error message
                example: api error message 
    NotFound:
      description: Queue not found
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                title: the response status code 
                default: 404
              message:
                type: string
                title: the error message
                example: api error message
    SuccessGetQueues:
      description: Success response
      content:
        application/json:
          schema:
            type: array
            title: alerts from GET
            items:
              $ref: '#/components/schemas/queue'
    SuccessGetQueue:
      description: Success response
      content:
        application/json:
          schema:
            type: object
            title: alerts from GET
            $ref: '#/components/schemas/queue'
    SuccessCreateQueue:
      description: Successfully created queue
      content:
        application/json:
          schema:
            type: object
            title: queue created after POST
            $ref: '#/components/schemas/queue'
    SuccessDeleteQueue:
      description: Success response

  schemas:
    queue:
      title: queue
      type: object
      properties:
        queueId:
          type: string
          title: queueId
        defaultTtl:
          type: integer
          title: defaultTtl
        defaultLockTtl:
          type: integer
          title: defaultLockTtl
        type:
          type: string
          title: type
        encrypted:
          type: boolean
          title: encrypted
        defaultDeliveryDelay:
          type: integer
          title: defaultDeliveryDelay
        fifo:
          type: boolean
          title: fifo

    queueBody:
      title: queueBody
      type: object
      properties:
        defaultTtl:
          type: integer
          title: defaultTtl
        defaultLockTtl:
          type: integer
          title: defaultLockTtl
        type:
          type: string
          title: type
        encrypted:
          type: boolean
          title: encrypted
        defaultDeliveryDelay:
          type: integer
          title: defaultDeliveryDelay
        fifo:
          type: boolean
          title: fifo

