openapi: 3.0.0 
info:
  title: Alert API Manager
  description: Alert for API Manager
  version: 1.0.0

servers:
  - url: https://anypoint.mulesoft.com/apimanager/api/v1/
    description: Anypoint Cloudhub 
  - url: https://eu1.anypoint.mulesoft.com/apimanager/api/v1/
    description: Anypoint Cloudhub EU
  - url: https://gov.anypoint.mulesoft.com/apimanager/api/v1/
    description: Anypoint Cloudhub GOV

security:
  - bearerAuth: [] 
      
paths:
  /organizations/{orgId}/environments/{envId}/apis/{apiVersion}/alerts:
    parameters:
      - in: path
        name: orgId
        description: The organization Id
        required: true
        schema:
          type: string
      - in: path
        name: envId
        description: The environment id
        required: true
        schema:
          type: string
      - in: path
        name: apiVersion
        description: The api version
        required: true
        schema:
          type: string
    get:
      summary: GetAlertsfromAPImanager
      description: Get Alerts from API manager
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':    # status code
          $ref: '#/components/responses/SuccessGetAlerts'
   
    post:
      description: Create a new alert for API manager
      operationId: CreateAlertForAPIManagerInstance
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/alertCore'
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '201':
        
          $ref: '#/components/responses/SuccessCreateAlert'
  
  
  /organizations/{orgId}/environments/{envId}/apis/{apiVersion}/alerts/{alertId}:
    parameters:
      - in: path
        name: orgId
        description: The organization Id
        required: true
        schema:
          type: string
      - in: path
        name: envId
        description: the environment id
        required: true
        schema:
          type: string
      - in: path
        name: apiVersion
        description: the api version
        required: true
        schema:
          type: string
      - name: alertId
        in: path
        description: the id of the alert
        required: true
        style: simple
        schema:
          type: string
    get:
      summary: Getonealert
      description: Get one alert
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':
          $ref: "#/components/responses/SuccessGetAlert"

    patch:
      summary: ModifyonealertfromAPImanger
      description: Modify one alert from API manger
      operationId: ModifyonealertfromAPImanger
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/alertCore'
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':
          $ref: '#/components/responses/SuccessGetAlert'
    
    delete:
      summary: DeleteanAlertfromAPImanager
      description: Delete an Alert from API manager
      operationId: DeleteanAlertfromAPImanager
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '204':
          $ref: '#/components/responses/SuccessDeleteAlert'

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    BadRequestError:
      description: Bad request response
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                title: the response status code 
                default: 400
              message:
                type: string
                title: the error message
                example: api error message 
    SuccessGetAlerts:
      description: Success response
      content:
        application/json:
          schema:
            type: array
            title: alerts from GET
            items:
              $ref: '#/components/schemas/alert'
    SuccessGetAlert:
      description: Success response
      content:
        application/json:
          schema:
            type: object
            title: alert from GET one alert
            $ref: '#/components/schemas/alert'
    SuccessCreateAlert:
      description: Success create an alert
      content:
        application/json:
          schema:
            type: object
            title: alert created after POST
            $ref: '#/components/schemas/alert'
    SuccessDeleteAlert:
      description: Success delete alert
      content: 
        text/plain:
          example:
            "successfully deleted"
      



  schemas:
    alert:
      title: alert
      allOf:
        - type: object
          title: alertId
          required:
            - id
          properties:
            id:
              type: string
              title: id
        - $ref: '#/components/schemas/alertCore'
    alertCore:
      title: alertCore
      required:
      - apiAlertsVersion
      - name
      - type
      - enabled
      - severity
      - recipients
      - condition
      - period
      type: object
      properties:
        apiAlertsVersion:
          type: string
        name: 
          type: string
        type:
          type: string
          title: type
        enabled:
          type: boolean
          title: enabled
        severity:
          type: string
          title: severity
        recipients:
          type: array
          title: recipients
          items:
            $ref: '#/components/schemas/recipient'
        condition:
          $ref: '#/components/schemas/condition'
        period:
          $ref: '#/components/schemas/period'
    recipient:
      title: recipient
      required:
      - type
      - value
      - firstName
      - lastName
      type: object
      properties:
        type:
          type: string
        value:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    condition:
      title: condition
      required:
      - resourceType
      - aggregate
      - operator
      - value
      type: object
      properties:
        resourceType:
          type: string
        aggregate:
          type: string
        operator:
          type: string
        value:
          type: integer
          format: int32
    period:
      title: period
      required:
      - duration
      - repeat
      type: object
      properties:
        duration:
          $ref: '#/components/schemas/duration'
        repeat:
          type: integer
          format: int32
    duration:
      title: duration
      required:
      - count
      - weight
      type: object
      properties:
        count:
          type: integer
          format: int32
        weight:
          type: string

