openapi: 3.0.0
info:
  title: Exchange Assets
  contact: {}
  version: '1.0'
servers:
- url: https://anypoint.mulesoft.com/exchange/api
  variables: {}
paths:
  /v2/assets:
    get:
      tags:
      - Misc
      summary: GetAsset
      description: Get Asset
      operationId: GetAsset
      parameters:
      - name: Authorization
        in: header
        description: ''
        style: simple
        schema:
          type: string
          default: Bearer {token}
      - name: search
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: types
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: domain
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: masterOrganizationId
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: offset
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: sharedWithMe
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: includeSnapshots
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: boolean
      responses:
        '200':
          description: ''
          headers: {}
          content: {}
      deprecated: false
  /v2/assets/{cloudhub-org}/{cloudhub-ex-asset}/asset:
    get:
      tags:
      - Misc
      summary: GetonespecificAsset
      description: Get one specific Asset
      operationId: GetonespecificAsset
      parameters:
      - name: Authorization
        in: header
        description: ''
        style: simple
        schema:
          type: string
          default: Bearer {token}
      - name: cloudhub-org
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: cloudhub-ex-asset
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
          content: {}
      deprecated: false
  /v2/assets/{cloudhub-org}/{cloudhub-ex-asset}:
    patch:
      tags:
      - Misc
      summary: Modifyanasset
      description: Modify an asset
      operationId: Modifyanasset
      parameters:
      - name: Authorization
        in: header
        description: ''
        style: simple
        schema:
          type: string
          default: Bearer {token}
      - name: cloudhub-org
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: cloudhub-ex-asset
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifyanassetRequest'
            example:
              description: postmanbbb{{$randomInt}}
        required: true
      responses:
        '200':
          description: ''
          headers: {}
          content: {}
      deprecated: false
  /v1/assets:
    post:
      tags:
      - Misc
      summary: Createanewasset
      description: Create a new asset
      operationId: Createanewasset
      parameters:
      - name: Authorization
        in: header
        description: ''
        style: simple
        schema:
          type: string
          default: Bearer {token}
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - organizationId
              - assetId
              - version
              - name
              - classifier
              - apiVersion
              - main
              - groupId
              - asset
              type: object
              properties:
                organizationId:
                  type: string
                assetId:
                  type: string
                version:
                  type: string
                name:
                  type: string
                classifier:
                  type: string
                apiVersion:
                  type: string
                main:
                  type: string
                groupId:
                  type: string
                asset:
                  type: string
        required: false
      responses:
        '200':
          description: ''
          headers: {}
          content: {}
      deprecated: false
  /v2/assets/{cloudhub-org}/{cloudhub-ex-asset}/{cloudhub-ex-version}:
    delete:
      tags:
      - Misc
      summary: Deleteanasset
      description: Delete an asset
      operationId: Deleteanasset
      parameters:
      - name: Authorization
        in: header
        description: ''
        style: simple
        schema:
          type: string
          default: Bearer {token}
      - name: x-delete-type
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: cloudhub-org
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: cloudhub-ex-asset
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: cloudhub-ex-version
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
          content: {}
      deprecated: false
components:
  schemas:
    ModifyanassetRequest:
      title: ModifyanassetRequest
      required:
      - description
      type: object
      properties:
        description:
          type: string
      example:
        description: postmanbbb{{$randomInt}}
tags:
- name: Misc
  description: ''
