openapi: 3.0.0
info:
  title: Invite API
  description: Description of the Invite API 
  version: 1.0.0
servers:
  - url: https://anypoint.mulesoft.com/accounts/api/
    description: Anypoint Cloudhub 
  - url: https://eu1.anypoint.mulesoft.com/accounts/api/
    description: Anypoint Cloudhub EU
  - url: https://gov.anypoint.mulesoft.com/accounts/api/
    description: Anypoint Cloudhub GOV

security:
  - bearerAuth: [] 

paths:
  /organizations/{orgId}/invites:
    get:
      description: Returns outstanding or expired invites
      parameters:
        - name: orgId
          in: path
          description: The ID of the organization in GUID format
          required: true
          schema:
            type: string
        - name: search
          in: query
          description: A search string to use for partial matches of invited emails
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Pagination parameter for choosing how many results include in the response
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: Pagination parameter to start returning results from the specified position of matches
          required: false
          schema:
            type: integer
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':    # status code
          $ref: '#/components/responses/SuccessListInvites'
    post:
      description: Creates an invite
      parameters:
      - name: orgId
        in: path
        description: The ID of the organization in GUID format
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/invitePostBody'
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '201':
          $ref: '#/components/responses/SuccessPostInvite'
    delete:
      description: Delete one or more invites
      parameters:
      - name: orgId
        in: path
        description: The ID of the organization in GUID format
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/invitesDeleteBody'
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '204':
          $ref: '#/components/responses/SuccessDeleteInvites'



components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    BadRequestError:
      description: Bad request response
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                title: the response status code 
                default: 400
              message:
                type: string
                title: the error message
                example: A sample message here 
    SuccessPostInvite:
      description: Success response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/invite'
    SuccessDeleteInvites:
      description: Success response
    SuccessListInvites:
      description: Success response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                title: List of invites
                items:
                  $ref: '#/components/schemas/invite'
              total:
                type: integer
                title: Total number of results

  schemas:
    invitePostBody:
      type: object
      title: invitePostBody
      properties:
        email:
          type: string
          title: email 
        role_groups:
          type: object
          title: roleGroups
          properties:
            role_group_id:
              type: string
              title: roleGroupId
            name:
              type: string
              title: name
    invitesDeleteBody:
      type: array
      title: invitesDeleteBody
      items:
        type: object
        title: inviteDelete
        properties:
          inviteId:
            type: string
            title: inviteId
    invite:
      title: invite
      allOf:
        - type: object
          title: inviteObjId
          required:
            - id
          properties:
            id:
              title: id
              type: string
        - $ref: "#/components/schemas/inviteCore"
    inviteCore:
      title: inviteCore
      type: object
      properties:
        code:
          type: string
          title: code
        invited_at:
          type: string
          title: invitedAt
        invited_email:
          type: string
          title: invitedEmail
        expires_at:
          type: string
          title: expiresAt
        status:
          type: string
          title: status
