openapi: 3.0.0

info:
  title: Message Queue
  description: Manage Queues in Cloudhub
  version: 1.0.0
 
servers:
  - url: https://anypoint.mulesoft.com/mq/admin/api/
    description: Anypoint Cloudhub MQ

security:
  - bearerAuth: [] 
      
paths:
  /v1/organizations/{orgId}/environments/{envId}/regions/{regionId}/destinations:
    parameters:
      - in: path
        name: orgId
        description: The organization Id
        required: true
        schema:
          type: string
      - in: path
        name: envId
        description: The environment id
        required: true
        schema:
          type: string
      - in: path
        name: regionId
        description: The region id for MQ
        required: true
        schema:
          type: string
    get:
      description: Get a list of queues in a region
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':
          $ref: '#/components/responses/SuccessGetQueues'
  /v1/organizations/{orgId}/environments/{envId}/regions/{regionId}/destinations/queues/{queueId}:
    parameters:
      - in: path
        name: orgId
        description: The organization Id
        required: true
        schema:
          type: string
      - in: path
        name: envId
        description: The environment id
        required: true
        schema:
          type: string
      - in: path
        name: regionId
        description: The region id
        required: true
        schema:
          type: string
      - in: path
        name: queueId
        description: The id of a specific queue
        required: true
        schema:
          type: string
    
    get:
      description: Get details about a queue
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':
          $ref: '#/components/responses/SuccessGetQueue'
    patch:
      description: Modify a queue's properties
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFound'
        '200':
          $ref: '#/components/responses/SuccessGetQueue'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueueOptional'
    put:
      description: Create queue      
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':
          $ref: '#/components/responses/SuccessGetQueue'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueueOptional'
    delete:
      description: Delete queue 
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '204':
          $ref: '#/components/responses/SuccessDeleteQueue'

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    BadRequestError:
      description: Bad request response
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                title: the response status code 
                default: 400
              message:
                type: string
                title: the error message
                example: api error message 
    NotFound:
      description: Queue not found
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                title: the response status code 
                default: 404
              message:
                type: string
                title: the error message
                example: api error message
    SuccessGetQueues:
      description: Success response
      content:
        application/json:
          schema:
            type: array
            title: alerts from GET
            items:
              $ref: '#/components/schemas/Queue'
    SuccessGetQueue:
      description: Success response
      content:
        application/json:
          schema:
            type: object
            title: alerts from GET
            $ref: '#/components/schemas/Queue'
    SuccessCreateQueue:
      description: Successfully created queue
      content:
        application/json:
          schema:
            type: object
            title: queue created after POST
            $ref: '#/components/schemas/Queue'
    SuccessDeleteQueue:
      description: Success response

  schemas:
    Queue:
      title: Queue
      required:
      - defaultTtl
      - defaultLockTtl
      - type
      - encrypted
      type: object
      properties:
        defaultTtl:
          type: integer
          format: int32
        defaultLockTtl:
          type: integer
          format: int32
        type:
          type: string
        encrypted:
          type: boolean
        defaultDeliveryDelay:
          type: integer
          format: int32
        fifo:
          type: boolean
    QueueOptional:
      title: Queue with optional properties
      type: object
      properties:
        defaultTtl:
          type: integer
          format: int32
        defaultLockTtl:
          type: integer
          format: int32
        type:
          type: string
        encrypted:
          type: boolean
        defaultDeliveryDelay:
          type: integer
          format: int32
        fifo:
          type: boolean

