/*
 * Partner Manager Partners API
 *
 * Anypoint Partner Manager - Partners API
 *
 * API version: v1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apm

import (
	"encoding/json"
)

// AckConfigX12 struct for AckConfigX12
type AckConfigX12 struct {
	BaseAckConfig
	Require997 *bool `json:"require997,omitempty"`
	Generate999 *bool `json:"generate999,omitempty"`
}

// NewAckConfigX12 instantiates a new AckConfigX12 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAckConfigX12(ackConfigType string) *AckConfigX12 {
	this := AckConfigX12{}
	this.AckConfigType = ackConfigType
	return &this
}

// NewAckConfigX12WithDefaults instantiates a new AckConfigX12 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAckConfigX12WithDefaults() *AckConfigX12 {
	this := AckConfigX12{}
	return &this
}

// GetRequire997 returns the Require997 field value if set, zero value otherwise.
func (o *AckConfigX12) GetRequire997() bool {
	if o == nil || o.Require997 == nil {
		var ret bool
		return ret
	}
	return *o.Require997
}

// GetRequire997Ok returns a tuple with the Require997 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AckConfigX12) GetRequire997Ok() (*bool, bool) {
	if o == nil || o.Require997 == nil {
		return nil, false
	}
	return o.Require997, true
}

// HasRequire997 returns a boolean if a field has been set.
func (o *AckConfigX12) HasRequire997() bool {
	if o != nil && o.Require997 != nil {
		return true
	}

	return false
}

// SetRequire997 gets a reference to the given bool and assigns it to the Require997 field.
func (o *AckConfigX12) SetRequire997(v bool) {
	o.Require997 = &v
}

// GetGenerate999 returns the Generate999 field value if set, zero value otherwise.
func (o *AckConfigX12) GetGenerate999() bool {
	if o == nil || o.Generate999 == nil {
		var ret bool
		return ret
	}
	return *o.Generate999
}

// GetGenerate999Ok returns a tuple with the Generate999 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AckConfigX12) GetGenerate999Ok() (*bool, bool) {
	if o == nil || o.Generate999 == nil {
		return nil, false
	}
	return o.Generate999, true
}

// HasGenerate999 returns a boolean if a field has been set.
func (o *AckConfigX12) HasGenerate999() bool {
	if o != nil && o.Generate999 != nil {
		return true
	}

	return false
}

// SetGenerate999 gets a reference to the given bool and assigns it to the Generate999 field.
func (o *AckConfigX12) SetGenerate999(v bool) {
	o.Generate999 = &v
}

func (o AckConfigX12) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseAckConfig, errBaseAckConfig := json.Marshal(o.BaseAckConfig)
	if errBaseAckConfig != nil {
		return []byte{}, errBaseAckConfig
	}
	errBaseAckConfig = json.Unmarshal([]byte(serializedBaseAckConfig), &toSerialize)
	if errBaseAckConfig != nil {
		return []byte{}, errBaseAckConfig
	}
	if o.Require997 != nil {
		toSerialize["require997"] = o.Require997
	}
	if o.Generate999 != nil {
		toSerialize["generate999"] = o.Generate999
	}
	return json.Marshal(toSerialize)
}

type NullableAckConfigX12 struct {
	value *AckConfigX12
	isSet bool
}

func (v NullableAckConfigX12) Get() *AckConfigX12 {
	return v.value
}

func (v *NullableAckConfigX12) Set(val *AckConfigX12) {
	v.value = val
	v.isSet = true
}

func (v NullableAckConfigX12) IsSet() bool {
	return v.isSet
}

func (v *NullableAckConfigX12) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAckConfigX12(val *AckConfigX12) *NullableAckConfigX12 {
	return &NullableAckConfigX12{value: val, isSet: true}
}

func (v NullableAckConfigX12) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAckConfigX12) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


