/*
 * Partner Manager Partners API
 *
 * Anypoint Partner Manager - Partners API
 *
 * API version: v1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apm

import (
	"encoding/json"
	"fmt"
)

// DeploymentStatusType the model 'DeploymentStatusType'
type DeploymentStatusType string

// List of DeploymentStatusType
const (
	ACTIVE DeploymentStatusType = "ACTIVE"
	INACTIVE DeploymentStatusType = "INACTIVE"
	DRAFT DeploymentStatusType = "DRAFT"
	FAIL DeploymentStatusType = "FAIL"
)

func (v *DeploymentStatusType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DeploymentStatusType(value)
	for _, existing := range []DeploymentStatusType{ "ACTIVE", "INACTIVE", "DRAFT", "FAIL",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DeploymentStatusType", value)
}

// Ptr returns reference to DeploymentStatusType value
func (v DeploymentStatusType) Ptr() *DeploymentStatusType {
	return &v
}

type NullableDeploymentStatusType struct {
	value *DeploymentStatusType
	isSet bool
}

func (v NullableDeploymentStatusType) Get() *DeploymentStatusType {
	return v.value
}

func (v *NullableDeploymentStatusType) Set(val *DeploymentStatusType) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentStatusType) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentStatusType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentStatusType(val *DeploymentStatusType) *NullableDeploymentStatusType {
	return &NullableDeploymentStatusType{value: val, isSet: true}
}

func (v NullableDeploymentStatusType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentStatusType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

