/*
 * Partner Manager Partners API
 *
 * Anypoint Partner Manager - Partners API
 *
 * API version: v1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apm

import (
	"encoding/json"
)

// DeploymentPostRequest This is used for posting a new deployment for a message flow.
type DeploymentPostRequest struct {
	DocumentFlowId string `json:"documentFlowId"`
}

// NewDeploymentPostRequest instantiates a new DeploymentPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentPostRequest(documentFlowId string) *DeploymentPostRequest {
	this := DeploymentPostRequest{}
	this.DocumentFlowId = documentFlowId
	return &this
}

// NewDeploymentPostRequestWithDefaults instantiates a new DeploymentPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentPostRequestWithDefaults() *DeploymentPostRequest {
	this := DeploymentPostRequest{}
	return &this
}

// GetDocumentFlowId returns the DocumentFlowId field value
func (o *DeploymentPostRequest) GetDocumentFlowId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentFlowId
}

// GetDocumentFlowIdOk returns a tuple with the DocumentFlowId field value
// and a boolean to check if the value has been set.
func (o *DeploymentPostRequest) GetDocumentFlowIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DocumentFlowId, true
}

// SetDocumentFlowId sets field value
func (o *DeploymentPostRequest) SetDocumentFlowId(v string) {
	o.DocumentFlowId = v
}

func (o DeploymentPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["documentFlowId"] = o.DocumentFlowId
	}
	return json.Marshal(toSerialize)
}

type NullableDeploymentPostRequest struct {
	value *DeploymentPostRequest
	isSet bool
}

func (v NullableDeploymentPostRequest) Get() *DeploymentPostRequest {
	return v.value
}

func (v *NullableDeploymentPostRequest) Set(val *DeploymentPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentPostRequest(val *DeploymentPostRequest) *NullableDeploymentPostRequest {
	return &NullableDeploymentPostRequest{value: val, isSet: true}
}

func (v NullableDeploymentPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


