/*
 * Partner Manager Partners API
 *
 * Anypoint Partner Manager - Partners API
 *
 * API version: v1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apm

import (
	"encoding/json"
	"time"
)

// PartnerProfile Partner Profile Type
type PartnerProfile struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	WebsiteUrl *string `json:"websiteUrl,omitempty"`
	Status *TimedStatus `json:"status,omitempty"`
	EnvironmentId string `json:"environmentId"`
	HostFlag bool `json:"hostFlag"`
	Logo *Logo `json:"logo,omitempty"`
	Contacts *[]Contact `json:"contacts,omitempty"`
	Identifiers []Identifier `json:"identifiers"`
	Addresses *[]Address `json:"addresses,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	CreatedBy UserDetail `json:"created_by"`
	UpdatedAt time.Time `json:"updated_at"`
	UpdatedBy UserDetail `json:"updated_by"`
	Protocols []string `json:"protocols"`
	Standars []string `json:"standars"`
	UsedInDeployments UsedInDeployments `json:"usedInDeployments"`
}

// NewPartnerProfile instantiates a new PartnerProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerProfile(id string, name string, environmentId string, hostFlag bool, identifiers []Identifier, createdAt time.Time, createdBy UserDetail, updatedAt time.Time, updatedBy UserDetail, protocols []string, standars []string, usedInDeployments UsedInDeployments) *PartnerProfile {
	this := PartnerProfile{}
	this.Id = id
	this.Name = name
	this.EnvironmentId = environmentId
	this.HostFlag = hostFlag
	this.Identifiers = identifiers
	this.CreatedAt = createdAt
	this.CreatedBy = createdBy
	this.UpdatedAt = updatedAt
	this.UpdatedBy = updatedBy
	this.Protocols = protocols
	this.Standars = standars
	this.UsedInDeployments = usedInDeployments
	return &this
}

// NewPartnerProfileWithDefaults instantiates a new PartnerProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerProfileWithDefaults() *PartnerProfile {
	this := PartnerProfile{}
	var hostFlag bool = false
	this.HostFlag = hostFlag
	return &this
}

// GetId returns the Id field value
func (o *PartnerProfile) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PartnerProfile) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *PartnerProfile) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PartnerProfile) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PartnerProfile) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PartnerProfile) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PartnerProfile) SetDescription(v string) {
	o.Description = &v
}

// GetWebsiteUrl returns the WebsiteUrl field value if set, zero value otherwise.
func (o *PartnerProfile) GetWebsiteUrl() string {
	if o == nil || o.WebsiteUrl == nil {
		var ret string
		return ret
	}
	return *o.WebsiteUrl
}

// GetWebsiteUrlOk returns a tuple with the WebsiteUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetWebsiteUrlOk() (*string, bool) {
	if o == nil || o.WebsiteUrl == nil {
		return nil, false
	}
	return o.WebsiteUrl, true
}

// HasWebsiteUrl returns a boolean if a field has been set.
func (o *PartnerProfile) HasWebsiteUrl() bool {
	if o != nil && o.WebsiteUrl != nil {
		return true
	}

	return false
}

// SetWebsiteUrl gets a reference to the given string and assigns it to the WebsiteUrl field.
func (o *PartnerProfile) SetWebsiteUrl(v string) {
	o.WebsiteUrl = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PartnerProfile) GetStatus() TimedStatus {
	if o == nil || o.Status == nil {
		var ret TimedStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetStatusOk() (*TimedStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PartnerProfile) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given TimedStatus and assigns it to the Status field.
func (o *PartnerProfile) SetStatus(v TimedStatus) {
	o.Status = &v
}

// GetEnvironmentId returns the EnvironmentId field value
func (o *PartnerProfile) GetEnvironmentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentId
}

// GetEnvironmentIdOk returns a tuple with the EnvironmentId field value
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetEnvironmentIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.EnvironmentId, true
}

// SetEnvironmentId sets field value
func (o *PartnerProfile) SetEnvironmentId(v string) {
	o.EnvironmentId = v
}

// GetHostFlag returns the HostFlag field value
func (o *PartnerProfile) GetHostFlag() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HostFlag
}

// GetHostFlagOk returns a tuple with the HostFlag field value
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetHostFlagOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.HostFlag, true
}

// SetHostFlag sets field value
func (o *PartnerProfile) SetHostFlag(v bool) {
	o.HostFlag = v
}

// GetLogo returns the Logo field value if set, zero value otherwise.
func (o *PartnerProfile) GetLogo() Logo {
	if o == nil || o.Logo == nil {
		var ret Logo
		return ret
	}
	return *o.Logo
}

// GetLogoOk returns a tuple with the Logo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetLogoOk() (*Logo, bool) {
	if o == nil || o.Logo == nil {
		return nil, false
	}
	return o.Logo, true
}

// HasLogo returns a boolean if a field has been set.
func (o *PartnerProfile) HasLogo() bool {
	if o != nil && o.Logo != nil {
		return true
	}

	return false
}

// SetLogo gets a reference to the given Logo and assigns it to the Logo field.
func (o *PartnerProfile) SetLogo(v Logo) {
	o.Logo = &v
}

// GetContacts returns the Contacts field value if set, zero value otherwise.
func (o *PartnerProfile) GetContacts() []Contact {
	if o == nil || o.Contacts == nil {
		var ret []Contact
		return ret
	}
	return *o.Contacts
}

// GetContactsOk returns a tuple with the Contacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetContactsOk() (*[]Contact, bool) {
	if o == nil || o.Contacts == nil {
		return nil, false
	}
	return o.Contacts, true
}

// HasContacts returns a boolean if a field has been set.
func (o *PartnerProfile) HasContacts() bool {
	if o != nil && o.Contacts != nil {
		return true
	}

	return false
}

// SetContacts gets a reference to the given []Contact and assigns it to the Contacts field.
func (o *PartnerProfile) SetContacts(v []Contact) {
	o.Contacts = &v
}

// GetIdentifiers returns the Identifiers field value
func (o *PartnerProfile) GetIdentifiers() []Identifier {
	if o == nil {
		var ret []Identifier
		return ret
	}

	return o.Identifiers
}

// GetIdentifiersOk returns a tuple with the Identifiers field value
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetIdentifiersOk() (*[]Identifier, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Identifiers, true
}

// SetIdentifiers sets field value
func (o *PartnerProfile) SetIdentifiers(v []Identifier) {
	o.Identifiers = v
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *PartnerProfile) GetAddresses() []Address {
	if o == nil || o.Addresses == nil {
		var ret []Address
		return ret
	}
	return *o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetAddressesOk() (*[]Address, bool) {
	if o == nil || o.Addresses == nil {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *PartnerProfile) HasAddresses() bool {
	if o != nil && o.Addresses != nil {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given []Address and assigns it to the Addresses field.
func (o *PartnerProfile) SetAddresses(v []Address) {
	o.Addresses = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PartnerProfile) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PartnerProfile) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *PartnerProfile) GetCreatedBy() UserDetail {
	if o == nil {
		var ret UserDetail
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetCreatedByOk() (*UserDetail, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *PartnerProfile) SetCreatedBy(v UserDetail) {
	o.CreatedBy = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *PartnerProfile) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *PartnerProfile) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetUpdatedBy returns the UpdatedBy field value
func (o *PartnerProfile) GetUpdatedBy() UserDetail {
	if o == nil {
		var ret UserDetail
		return ret
	}

	return o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetUpdatedByOk() (*UserDetail, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UpdatedBy, true
}

// SetUpdatedBy sets field value
func (o *PartnerProfile) SetUpdatedBy(v UserDetail) {
	o.UpdatedBy = v
}

// GetProtocols returns the Protocols field value
func (o *PartnerProfile) GetProtocols() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Protocols
}

// GetProtocolsOk returns a tuple with the Protocols field value
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetProtocolsOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Protocols, true
}

// SetProtocols sets field value
func (o *PartnerProfile) SetProtocols(v []string) {
	o.Protocols = v
}

// GetStandars returns the Standars field value
func (o *PartnerProfile) GetStandars() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Standars
}

// GetStandarsOk returns a tuple with the Standars field value
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetStandarsOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Standars, true
}

// SetStandars sets field value
func (o *PartnerProfile) SetStandars(v []string) {
	o.Standars = v
}

// GetUsedInDeployments returns the UsedInDeployments field value
func (o *PartnerProfile) GetUsedInDeployments() UsedInDeployments {
	if o == nil {
		var ret UsedInDeployments
		return ret
	}

	return o.UsedInDeployments
}

// GetUsedInDeploymentsOk returns a tuple with the UsedInDeployments field value
// and a boolean to check if the value has been set.
func (o *PartnerProfile) GetUsedInDeploymentsOk() (*UsedInDeployments, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UsedInDeployments, true
}

// SetUsedInDeployments sets field value
func (o *PartnerProfile) SetUsedInDeployments(v UsedInDeployments) {
	o.UsedInDeployments = v
}

func (o PartnerProfile) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.WebsiteUrl != nil {
		toSerialize["websiteUrl"] = o.WebsiteUrl
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["environmentId"] = o.EnvironmentId
	}
	if true {
		toSerialize["hostFlag"] = o.HostFlag
	}
	if o.Logo != nil {
		toSerialize["logo"] = o.Logo
	}
	if o.Contacts != nil {
		toSerialize["contacts"] = o.Contacts
	}
	if true {
		toSerialize["identifiers"] = o.Identifiers
	}
	if o.Addresses != nil {
		toSerialize["addresses"] = o.Addresses
	}
	if true {
		toSerialize["created_at"] = o.CreatedAt
	}
	if true {
		toSerialize["created_by"] = o.CreatedBy
	}
	if true {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if true {
		toSerialize["updated_by"] = o.UpdatedBy
	}
	if true {
		toSerialize["protocols"] = o.Protocols
	}
	if true {
		toSerialize["standars"] = o.Standars
	}
	if true {
		toSerialize["usedInDeployments"] = o.UsedInDeployments
	}
	return json.Marshal(toSerialize)
}

type NullablePartnerProfile struct {
	value *PartnerProfile
	isSet bool
}

func (v NullablePartnerProfile) Get() *PartnerProfile {
	return v.value
}

func (v *NullablePartnerProfile) Set(val *PartnerProfile) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerProfile) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerProfile(val *PartnerProfile) *NullablePartnerProfile {
	return &NullablePartnerProfile{value: val, isSet: true}
}

func (v NullablePartnerProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


