/*
 * Partner Manager Partners API
 *
 * Anypoint Partner Manager - Partners API
 *
 * API version: v1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apm

import (
	"encoding/json"
)

// CSMSecret This holds the CSM Secret details
type CSMSecret struct {
	SecretId string `json:"secretId"`
	SecretGroupId string `json:"secretGroupId"`
	GrantResponse CSMSecretGrant `json:"grantResponse"`
	JsonDetails NullableString `json:"jsonDetails,omitempty"`
}

// NewCSMSecret instantiates a new CSMSecret object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCSMSecret(secretId string, secretGroupId string, grantResponse CSMSecretGrant) *CSMSecret {
	this := CSMSecret{}
	this.SecretId = secretId
	this.SecretGroupId = secretGroupId
	this.GrantResponse = grantResponse
	return &this
}

// NewCSMSecretWithDefaults instantiates a new CSMSecret object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCSMSecretWithDefaults() *CSMSecret {
	this := CSMSecret{}
	return &this
}

// GetSecretId returns the SecretId field value
func (o *CSMSecret) GetSecretId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretId
}

// GetSecretIdOk returns a tuple with the SecretId field value
// and a boolean to check if the value has been set.
func (o *CSMSecret) GetSecretIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SecretId, true
}

// SetSecretId sets field value
func (o *CSMSecret) SetSecretId(v string) {
	o.SecretId = v
}

// GetSecretGroupId returns the SecretGroupId field value
func (o *CSMSecret) GetSecretGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretGroupId
}

// GetSecretGroupIdOk returns a tuple with the SecretGroupId field value
// and a boolean to check if the value has been set.
func (o *CSMSecret) GetSecretGroupIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SecretGroupId, true
}

// SetSecretGroupId sets field value
func (o *CSMSecret) SetSecretGroupId(v string) {
	o.SecretGroupId = v
}

// GetGrantResponse returns the GrantResponse field value
func (o *CSMSecret) GetGrantResponse() CSMSecretGrant {
	if o == nil {
		var ret CSMSecretGrant
		return ret
	}

	return o.GrantResponse
}

// GetGrantResponseOk returns a tuple with the GrantResponse field value
// and a boolean to check if the value has been set.
func (o *CSMSecret) GetGrantResponseOk() (*CSMSecretGrant, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.GrantResponse, true
}

// SetGrantResponse sets field value
func (o *CSMSecret) SetGrantResponse(v CSMSecretGrant) {
	o.GrantResponse = v
}

// GetJsonDetails returns the JsonDetails field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSMSecret) GetJsonDetails() string {
	if o == nil || o.JsonDetails.Get() == nil {
		var ret string
		return ret
	}
	return *o.JsonDetails.Get()
}

// GetJsonDetailsOk returns a tuple with the JsonDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSMSecret) GetJsonDetailsOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.JsonDetails.Get(), o.JsonDetails.IsSet()
}

// HasJsonDetails returns a boolean if a field has been set.
func (o *CSMSecret) HasJsonDetails() bool {
	if o != nil && o.JsonDetails.IsSet() {
		return true
	}

	return false
}

// SetJsonDetails gets a reference to the given NullableString and assigns it to the JsonDetails field.
func (o *CSMSecret) SetJsonDetails(v string) {
	o.JsonDetails.Set(&v)
}
// SetJsonDetailsNil sets the value for JsonDetails to be an explicit nil
func (o *CSMSecret) SetJsonDetailsNil() {
	o.JsonDetails.Set(nil)
}

// UnsetJsonDetails ensures that no value is present for JsonDetails, not even an explicit nil
func (o *CSMSecret) UnsetJsonDetails() {
	o.JsonDetails.Unset()
}

func (o CSMSecret) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["secretId"] = o.SecretId
	}
	if true {
		toSerialize["secretGroupId"] = o.SecretGroupId
	}
	if true {
		toSerialize["grantResponse"] = o.GrantResponse
	}
	if o.JsonDetails.IsSet() {
		toSerialize["jsonDetails"] = o.JsonDetails.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableCSMSecret struct {
	value *CSMSecret
	isSet bool
}

func (v NullableCSMSecret) Get() *CSMSecret {
	return v.value
}

func (v *NullableCSMSecret) Set(val *CSMSecret) {
	v.value = val
	v.isSet = true
}

func (v NullableCSMSecret) IsSet() bool {
	return v.isSet
}

func (v *NullableCSMSecret) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCSMSecret(val *CSMSecret) *NullableCSMSecret {
	return &NullableCSMSecret{value: val, isSet: true}
}

func (v NullableCSMSecret) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCSMSecret) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


