/*
 * Partner Manager Partners API
 *
 * Anypoint Partner Manager - Partners API
 *
 * API version: v1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apm

import (
	"encoding/json"
)

// EdiFormatConfigurationEdifactControlNumberSettings struct for EdiFormatConfigurationEdifactControlNumberSettings
type EdiFormatConfigurationEdifactControlNumberSettings struct {
	RequireUniqueInterchanges *bool `json:"requireUniqueInterchanges,omitempty"`
	RequireUniqueMessages *bool `json:"requireUniqueMessages,omitempty"`
	InitialControlNumber *string `json:"initialControlNumber,omitempty"`
}

// NewEdiFormatConfigurationEdifactControlNumberSettings instantiates a new EdiFormatConfigurationEdifactControlNumberSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEdiFormatConfigurationEdifactControlNumberSettings() *EdiFormatConfigurationEdifactControlNumberSettings {
	this := EdiFormatConfigurationEdifactControlNumberSettings{}
	return &this
}

// NewEdiFormatConfigurationEdifactControlNumberSettingsWithDefaults instantiates a new EdiFormatConfigurationEdifactControlNumberSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEdiFormatConfigurationEdifactControlNumberSettingsWithDefaults() *EdiFormatConfigurationEdifactControlNumberSettings {
	this := EdiFormatConfigurationEdifactControlNumberSettings{}
	return &this
}

// GetRequireUniqueInterchanges returns the RequireUniqueInterchanges field value if set, zero value otherwise.
func (o *EdiFormatConfigurationEdifactControlNumberSettings) GetRequireUniqueInterchanges() bool {
	if o == nil || o.RequireUniqueInterchanges == nil {
		var ret bool
		return ret
	}
	return *o.RequireUniqueInterchanges
}

// GetRequireUniqueInterchangesOk returns a tuple with the RequireUniqueInterchanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EdiFormatConfigurationEdifactControlNumberSettings) GetRequireUniqueInterchangesOk() (*bool, bool) {
	if o == nil || o.RequireUniqueInterchanges == nil {
		return nil, false
	}
	return o.RequireUniqueInterchanges, true
}

// HasRequireUniqueInterchanges returns a boolean if a field has been set.
func (o *EdiFormatConfigurationEdifactControlNumberSettings) HasRequireUniqueInterchanges() bool {
	if o != nil && o.RequireUniqueInterchanges != nil {
		return true
	}

	return false
}

// SetRequireUniqueInterchanges gets a reference to the given bool and assigns it to the RequireUniqueInterchanges field.
func (o *EdiFormatConfigurationEdifactControlNumberSettings) SetRequireUniqueInterchanges(v bool) {
	o.RequireUniqueInterchanges = &v
}

// GetRequireUniqueMessages returns the RequireUniqueMessages field value if set, zero value otherwise.
func (o *EdiFormatConfigurationEdifactControlNumberSettings) GetRequireUniqueMessages() bool {
	if o == nil || o.RequireUniqueMessages == nil {
		var ret bool
		return ret
	}
	return *o.RequireUniqueMessages
}

// GetRequireUniqueMessagesOk returns a tuple with the RequireUniqueMessages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EdiFormatConfigurationEdifactControlNumberSettings) GetRequireUniqueMessagesOk() (*bool, bool) {
	if o == nil || o.RequireUniqueMessages == nil {
		return nil, false
	}
	return o.RequireUniqueMessages, true
}

// HasRequireUniqueMessages returns a boolean if a field has been set.
func (o *EdiFormatConfigurationEdifactControlNumberSettings) HasRequireUniqueMessages() bool {
	if o != nil && o.RequireUniqueMessages != nil {
		return true
	}

	return false
}

// SetRequireUniqueMessages gets a reference to the given bool and assigns it to the RequireUniqueMessages field.
func (o *EdiFormatConfigurationEdifactControlNumberSettings) SetRequireUniqueMessages(v bool) {
	o.RequireUniqueMessages = &v
}

// GetInitialControlNumber returns the InitialControlNumber field value if set, zero value otherwise.
func (o *EdiFormatConfigurationEdifactControlNumberSettings) GetInitialControlNumber() string {
	if o == nil || o.InitialControlNumber == nil {
		var ret string
		return ret
	}
	return *o.InitialControlNumber
}

// GetInitialControlNumberOk returns a tuple with the InitialControlNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EdiFormatConfigurationEdifactControlNumberSettings) GetInitialControlNumberOk() (*string, bool) {
	if o == nil || o.InitialControlNumber == nil {
		return nil, false
	}
	return o.InitialControlNumber, true
}

// HasInitialControlNumber returns a boolean if a field has been set.
func (o *EdiFormatConfigurationEdifactControlNumberSettings) HasInitialControlNumber() bool {
	if o != nil && o.InitialControlNumber != nil {
		return true
	}

	return false
}

// SetInitialControlNumber gets a reference to the given string and assigns it to the InitialControlNumber field.
func (o *EdiFormatConfigurationEdifactControlNumberSettings) SetInitialControlNumber(v string) {
	o.InitialControlNumber = &v
}

func (o EdiFormatConfigurationEdifactControlNumberSettings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RequireUniqueInterchanges != nil {
		toSerialize["requireUniqueInterchanges"] = o.RequireUniqueInterchanges
	}
	if o.RequireUniqueMessages != nil {
		toSerialize["requireUniqueMessages"] = o.RequireUniqueMessages
	}
	if o.InitialControlNumber != nil {
		toSerialize["initialControlNumber"] = o.InitialControlNumber
	}
	return json.Marshal(toSerialize)
}

type NullableEdiFormatConfigurationEdifactControlNumberSettings struct {
	value *EdiFormatConfigurationEdifactControlNumberSettings
	isSet bool
}

func (v NullableEdiFormatConfigurationEdifactControlNumberSettings) Get() *EdiFormatConfigurationEdifactControlNumberSettings {
	return v.value
}

func (v *NullableEdiFormatConfigurationEdifactControlNumberSettings) Set(val *EdiFormatConfigurationEdifactControlNumberSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableEdiFormatConfigurationEdifactControlNumberSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableEdiFormatConfigurationEdifactControlNumberSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEdiFormatConfigurationEdifactControlNumberSettings(val *EdiFormatConfigurationEdifactControlNumberSettings) *NullableEdiFormatConfigurationEdifactControlNumberSettings {
	return &NullableEdiFormatConfigurationEdifactControlNumberSettings{value: val, isSet: true}
}

func (v NullableEdiFormatConfigurationEdifactControlNumberSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEdiFormatConfigurationEdifactControlNumberSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


