/*
 * Partner Manager Partners API
 *
 * Anypoint Partner Manager - Partners API
 *
 * API version: v1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apm

import (
	"encoding/json"
)

// EndpointConfigVpc struct for EndpointConfigVpc
type EndpointConfigVpc struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// NewEndpointConfigVpc instantiates a new EndpointConfigVpc object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointConfigVpc() *EndpointConfigVpc {
	this := EndpointConfigVpc{}
	return &this
}

// NewEndpointConfigVpcWithDefaults instantiates a new EndpointConfigVpc object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointConfigVpcWithDefaults() *EndpointConfigVpc {
	this := EndpointConfigVpc{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *EndpointConfigVpc) GetEnabled() bool {
	if o == nil || o.Enabled == nil {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointConfigVpc) GetEnabledOk() (*bool, bool) {
	if o == nil || o.Enabled == nil {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *EndpointConfigVpc) HasEnabled() bool {
	if o != nil && o.Enabled != nil {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *EndpointConfigVpc) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o EndpointConfigVpc) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	return json.Marshal(toSerialize)
}

type NullableEndpointConfigVpc struct {
	value *EndpointConfigVpc
	isSet bool
}

func (v NullableEndpointConfigVpc) Get() *EndpointConfigVpc {
	return v.value
}

func (v *NullableEndpointConfigVpc) Set(val *EndpointConfigVpc) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointConfigVpc) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointConfigVpc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointConfigVpc(val *EndpointConfigVpc) *NullableEndpointConfigVpc {
	return &NullableEndpointConfigVpc{value: val, isSet: true}
}

func (v NullableEndpointConfigVpc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointConfigVpc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


