/*
 * Partner Manager Partners API
 *
 * Anypoint Partner Manager - Partners API
 *
 * API version: v1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apm

import (
	"encoding/json"
)

// AuthModeClientCredentials This can be used for HTTP Outbound authentication.
type AuthModeClientCredentials struct {
	AuthModeBaseConfig
	ClientId *string `json:"clientId,omitempty"`
	ClientSecret *string `json:"clientSecret,omitempty"`
}

// NewAuthModeClientCredentials instantiates a new AuthModeClientCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthModeClientCredentials(authType string) *AuthModeClientCredentials {
	this := AuthModeClientCredentials{}
	this.AuthType = authType
	return &this
}

// NewAuthModeClientCredentialsWithDefaults instantiates a new AuthModeClientCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthModeClientCredentialsWithDefaults() *AuthModeClientCredentials {
	this := AuthModeClientCredentials{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *AuthModeClientCredentials) GetClientId() string {
	if o == nil || o.ClientId == nil {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthModeClientCredentials) GetClientIdOk() (*string, bool) {
	if o == nil || o.ClientId == nil {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *AuthModeClientCredentials) HasClientId() bool {
	if o != nil && o.ClientId != nil {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *AuthModeClientCredentials) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *AuthModeClientCredentials) GetClientSecret() string {
	if o == nil || o.ClientSecret == nil {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthModeClientCredentials) GetClientSecretOk() (*string, bool) {
	if o == nil || o.ClientSecret == nil {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *AuthModeClientCredentials) HasClientSecret() bool {
	if o != nil && o.ClientSecret != nil {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *AuthModeClientCredentials) SetClientSecret(v string) {
	o.ClientSecret = &v
}

func (o AuthModeClientCredentials) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedAuthModeBaseConfig, errAuthModeBaseConfig := json.Marshal(o.AuthModeBaseConfig)
	if errAuthModeBaseConfig != nil {
		return []byte{}, errAuthModeBaseConfig
	}
	errAuthModeBaseConfig = json.Unmarshal([]byte(serializedAuthModeBaseConfig), &toSerialize)
	if errAuthModeBaseConfig != nil {
		return []byte{}, errAuthModeBaseConfig
	}
	if o.ClientId != nil {
		toSerialize["clientId"] = o.ClientId
	}
	if o.ClientSecret != nil {
		toSerialize["clientSecret"] = o.ClientSecret
	}
	return json.Marshal(toSerialize)
}

type NullableAuthModeClientCredentials struct {
	value *AuthModeClientCredentials
	isSet bool
}

func (v NullableAuthModeClientCredentials) Get() *AuthModeClientCredentials {
	return v.value
}

func (v *NullableAuthModeClientCredentials) Set(val *AuthModeClientCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthModeClientCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthModeClientCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthModeClientCredentials(val *AuthModeClientCredentials) *NullableAuthModeClientCredentials {
	return &NullableAuthModeClientCredentials{value: val, isSet: true}
}

func (v NullableAuthModeClientCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthModeClientCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


