/*
 * Partner Manager Partners API
 *
 * Anypoint Partner Manager - Partners API
 *
 * API version: v1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apm

import (
	"encoding/json"
)

// EdiFormatConfigurationControlNumberSettings struct for EdiFormatConfigurationControlNumberSettings
type EdiFormatConfigurationControlNumberSettings struct {
	InitialInterchangeControlNumber *string `json:"initialInterchangeControlNumber,omitempty"`
	InitialGSControlNumber *string `json:"initialGSControlNumber,omitempty"`
	InitialTransactionSetControlNumber *string `json:"initialTransactionSetControlNumber,omitempty"`
	RequireUniqueGSControlNumbers *bool `json:"requireUniqueGSControlNumbers,omitempty"`
	RequireUniqueTransactionSetControlNumber *bool `json:"requireUniqueTransactionSetControlNumber,omitempty"`
	RequireUniqueISAcontrolNumbersISA13 *bool `json:"requireUniqueISAcontrolNumbersISA13,omitempty"`
	RequireUniqueGSControlNumbersGS06 *bool `json:"requireUniqueGSControlNumbersGS06,omitempty"`
	RequireUniqueTransactionSetControlNumbersST02 *bool `json:"requireUniqueTransactionSetControlNumbersST02,omitempty"`
}

// NewEdiFormatConfigurationControlNumberSettings instantiates a new EdiFormatConfigurationControlNumberSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEdiFormatConfigurationControlNumberSettings() *EdiFormatConfigurationControlNumberSettings {
	this := EdiFormatConfigurationControlNumberSettings{}
	return &this
}

// NewEdiFormatConfigurationControlNumberSettingsWithDefaults instantiates a new EdiFormatConfigurationControlNumberSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEdiFormatConfigurationControlNumberSettingsWithDefaults() *EdiFormatConfigurationControlNumberSettings {
	this := EdiFormatConfigurationControlNumberSettings{}
	return &this
}

// GetInitialInterchangeControlNumber returns the InitialInterchangeControlNumber field value if set, zero value otherwise.
func (o *EdiFormatConfigurationControlNumberSettings) GetInitialInterchangeControlNumber() string {
	if o == nil || o.InitialInterchangeControlNumber == nil {
		var ret string
		return ret
	}
	return *o.InitialInterchangeControlNumber
}

// GetInitialInterchangeControlNumberOk returns a tuple with the InitialInterchangeControlNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EdiFormatConfigurationControlNumberSettings) GetInitialInterchangeControlNumberOk() (*string, bool) {
	if o == nil || o.InitialInterchangeControlNumber == nil {
		return nil, false
	}
	return o.InitialInterchangeControlNumber, true
}

// HasInitialInterchangeControlNumber returns a boolean if a field has been set.
func (o *EdiFormatConfigurationControlNumberSettings) HasInitialInterchangeControlNumber() bool {
	if o != nil && o.InitialInterchangeControlNumber != nil {
		return true
	}

	return false
}

// SetInitialInterchangeControlNumber gets a reference to the given string and assigns it to the InitialInterchangeControlNumber field.
func (o *EdiFormatConfigurationControlNumberSettings) SetInitialInterchangeControlNumber(v string) {
	o.InitialInterchangeControlNumber = &v
}

// GetInitialGSControlNumber returns the InitialGSControlNumber field value if set, zero value otherwise.
func (o *EdiFormatConfigurationControlNumberSettings) GetInitialGSControlNumber() string {
	if o == nil || o.InitialGSControlNumber == nil {
		var ret string
		return ret
	}
	return *o.InitialGSControlNumber
}

// GetInitialGSControlNumberOk returns a tuple with the InitialGSControlNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EdiFormatConfigurationControlNumberSettings) GetInitialGSControlNumberOk() (*string, bool) {
	if o == nil || o.InitialGSControlNumber == nil {
		return nil, false
	}
	return o.InitialGSControlNumber, true
}

// HasInitialGSControlNumber returns a boolean if a field has been set.
func (o *EdiFormatConfigurationControlNumberSettings) HasInitialGSControlNumber() bool {
	if o != nil && o.InitialGSControlNumber != nil {
		return true
	}

	return false
}

// SetInitialGSControlNumber gets a reference to the given string and assigns it to the InitialGSControlNumber field.
func (o *EdiFormatConfigurationControlNumberSettings) SetInitialGSControlNumber(v string) {
	o.InitialGSControlNumber = &v
}

// GetInitialTransactionSetControlNumber returns the InitialTransactionSetControlNumber field value if set, zero value otherwise.
func (o *EdiFormatConfigurationControlNumberSettings) GetInitialTransactionSetControlNumber() string {
	if o == nil || o.InitialTransactionSetControlNumber == nil {
		var ret string
		return ret
	}
	return *o.InitialTransactionSetControlNumber
}

// GetInitialTransactionSetControlNumberOk returns a tuple with the InitialTransactionSetControlNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EdiFormatConfigurationControlNumberSettings) GetInitialTransactionSetControlNumberOk() (*string, bool) {
	if o == nil || o.InitialTransactionSetControlNumber == nil {
		return nil, false
	}
	return o.InitialTransactionSetControlNumber, true
}

// HasInitialTransactionSetControlNumber returns a boolean if a field has been set.
func (o *EdiFormatConfigurationControlNumberSettings) HasInitialTransactionSetControlNumber() bool {
	if o != nil && o.InitialTransactionSetControlNumber != nil {
		return true
	}

	return false
}

// SetInitialTransactionSetControlNumber gets a reference to the given string and assigns it to the InitialTransactionSetControlNumber field.
func (o *EdiFormatConfigurationControlNumberSettings) SetInitialTransactionSetControlNumber(v string) {
	o.InitialTransactionSetControlNumber = &v
}

// GetRequireUniqueGSControlNumbers returns the RequireUniqueGSControlNumbers field value if set, zero value otherwise.
func (o *EdiFormatConfigurationControlNumberSettings) GetRequireUniqueGSControlNumbers() bool {
	if o == nil || o.RequireUniqueGSControlNumbers == nil {
		var ret bool
		return ret
	}
	return *o.RequireUniqueGSControlNumbers
}

// GetRequireUniqueGSControlNumbersOk returns a tuple with the RequireUniqueGSControlNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EdiFormatConfigurationControlNumberSettings) GetRequireUniqueGSControlNumbersOk() (*bool, bool) {
	if o == nil || o.RequireUniqueGSControlNumbers == nil {
		return nil, false
	}
	return o.RequireUniqueGSControlNumbers, true
}

// HasRequireUniqueGSControlNumbers returns a boolean if a field has been set.
func (o *EdiFormatConfigurationControlNumberSettings) HasRequireUniqueGSControlNumbers() bool {
	if o != nil && o.RequireUniqueGSControlNumbers != nil {
		return true
	}

	return false
}

// SetRequireUniqueGSControlNumbers gets a reference to the given bool and assigns it to the RequireUniqueGSControlNumbers field.
func (o *EdiFormatConfigurationControlNumberSettings) SetRequireUniqueGSControlNumbers(v bool) {
	o.RequireUniqueGSControlNumbers = &v
}

// GetRequireUniqueTransactionSetControlNumber returns the RequireUniqueTransactionSetControlNumber field value if set, zero value otherwise.
func (o *EdiFormatConfigurationControlNumberSettings) GetRequireUniqueTransactionSetControlNumber() bool {
	if o == nil || o.RequireUniqueTransactionSetControlNumber == nil {
		var ret bool
		return ret
	}
	return *o.RequireUniqueTransactionSetControlNumber
}

// GetRequireUniqueTransactionSetControlNumberOk returns a tuple with the RequireUniqueTransactionSetControlNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EdiFormatConfigurationControlNumberSettings) GetRequireUniqueTransactionSetControlNumberOk() (*bool, bool) {
	if o == nil || o.RequireUniqueTransactionSetControlNumber == nil {
		return nil, false
	}
	return o.RequireUniqueTransactionSetControlNumber, true
}

// HasRequireUniqueTransactionSetControlNumber returns a boolean if a field has been set.
func (o *EdiFormatConfigurationControlNumberSettings) HasRequireUniqueTransactionSetControlNumber() bool {
	if o != nil && o.RequireUniqueTransactionSetControlNumber != nil {
		return true
	}

	return false
}

// SetRequireUniqueTransactionSetControlNumber gets a reference to the given bool and assigns it to the RequireUniqueTransactionSetControlNumber field.
func (o *EdiFormatConfigurationControlNumberSettings) SetRequireUniqueTransactionSetControlNumber(v bool) {
	o.RequireUniqueTransactionSetControlNumber = &v
}

// GetRequireUniqueISAcontrolNumbersISA13 returns the RequireUniqueISAcontrolNumbersISA13 field value if set, zero value otherwise.
func (o *EdiFormatConfigurationControlNumberSettings) GetRequireUniqueISAcontrolNumbersISA13() bool {
	if o == nil || o.RequireUniqueISAcontrolNumbersISA13 == nil {
		var ret bool
		return ret
	}
	return *o.RequireUniqueISAcontrolNumbersISA13
}

// GetRequireUniqueISAcontrolNumbersISA13Ok returns a tuple with the RequireUniqueISAcontrolNumbersISA13 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EdiFormatConfigurationControlNumberSettings) GetRequireUniqueISAcontrolNumbersISA13Ok() (*bool, bool) {
	if o == nil || o.RequireUniqueISAcontrolNumbersISA13 == nil {
		return nil, false
	}
	return o.RequireUniqueISAcontrolNumbersISA13, true
}

// HasRequireUniqueISAcontrolNumbersISA13 returns a boolean if a field has been set.
func (o *EdiFormatConfigurationControlNumberSettings) HasRequireUniqueISAcontrolNumbersISA13() bool {
	if o != nil && o.RequireUniqueISAcontrolNumbersISA13 != nil {
		return true
	}

	return false
}

// SetRequireUniqueISAcontrolNumbersISA13 gets a reference to the given bool and assigns it to the RequireUniqueISAcontrolNumbersISA13 field.
func (o *EdiFormatConfigurationControlNumberSettings) SetRequireUniqueISAcontrolNumbersISA13(v bool) {
	o.RequireUniqueISAcontrolNumbersISA13 = &v
}

// GetRequireUniqueGSControlNumbersGS06 returns the RequireUniqueGSControlNumbersGS06 field value if set, zero value otherwise.
func (o *EdiFormatConfigurationControlNumberSettings) GetRequireUniqueGSControlNumbersGS06() bool {
	if o == nil || o.RequireUniqueGSControlNumbersGS06 == nil {
		var ret bool
		return ret
	}
	return *o.RequireUniqueGSControlNumbersGS06
}

// GetRequireUniqueGSControlNumbersGS06Ok returns a tuple with the RequireUniqueGSControlNumbersGS06 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EdiFormatConfigurationControlNumberSettings) GetRequireUniqueGSControlNumbersGS06Ok() (*bool, bool) {
	if o == nil || o.RequireUniqueGSControlNumbersGS06 == nil {
		return nil, false
	}
	return o.RequireUniqueGSControlNumbersGS06, true
}

// HasRequireUniqueGSControlNumbersGS06 returns a boolean if a field has been set.
func (o *EdiFormatConfigurationControlNumberSettings) HasRequireUniqueGSControlNumbersGS06() bool {
	if o != nil && o.RequireUniqueGSControlNumbersGS06 != nil {
		return true
	}

	return false
}

// SetRequireUniqueGSControlNumbersGS06 gets a reference to the given bool and assigns it to the RequireUniqueGSControlNumbersGS06 field.
func (o *EdiFormatConfigurationControlNumberSettings) SetRequireUniqueGSControlNumbersGS06(v bool) {
	o.RequireUniqueGSControlNumbersGS06 = &v
}

// GetRequireUniqueTransactionSetControlNumbersST02 returns the RequireUniqueTransactionSetControlNumbersST02 field value if set, zero value otherwise.
func (o *EdiFormatConfigurationControlNumberSettings) GetRequireUniqueTransactionSetControlNumbersST02() bool {
	if o == nil || o.RequireUniqueTransactionSetControlNumbersST02 == nil {
		var ret bool
		return ret
	}
	return *o.RequireUniqueTransactionSetControlNumbersST02
}

// GetRequireUniqueTransactionSetControlNumbersST02Ok returns a tuple with the RequireUniqueTransactionSetControlNumbersST02 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EdiFormatConfigurationControlNumberSettings) GetRequireUniqueTransactionSetControlNumbersST02Ok() (*bool, bool) {
	if o == nil || o.RequireUniqueTransactionSetControlNumbersST02 == nil {
		return nil, false
	}
	return o.RequireUniqueTransactionSetControlNumbersST02, true
}

// HasRequireUniqueTransactionSetControlNumbersST02 returns a boolean if a field has been set.
func (o *EdiFormatConfigurationControlNumberSettings) HasRequireUniqueTransactionSetControlNumbersST02() bool {
	if o != nil && o.RequireUniqueTransactionSetControlNumbersST02 != nil {
		return true
	}

	return false
}

// SetRequireUniqueTransactionSetControlNumbersST02 gets a reference to the given bool and assigns it to the RequireUniqueTransactionSetControlNumbersST02 field.
func (o *EdiFormatConfigurationControlNumberSettings) SetRequireUniqueTransactionSetControlNumbersST02(v bool) {
	o.RequireUniqueTransactionSetControlNumbersST02 = &v
}

func (o EdiFormatConfigurationControlNumberSettings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.InitialInterchangeControlNumber != nil {
		toSerialize["initialInterchangeControlNumber"] = o.InitialInterchangeControlNumber
	}
	if o.InitialGSControlNumber != nil {
		toSerialize["initialGSControlNumber"] = o.InitialGSControlNumber
	}
	if o.InitialTransactionSetControlNumber != nil {
		toSerialize["initialTransactionSetControlNumber"] = o.InitialTransactionSetControlNumber
	}
	if o.RequireUniqueGSControlNumbers != nil {
		toSerialize["requireUniqueGSControlNumbers"] = o.RequireUniqueGSControlNumbers
	}
	if o.RequireUniqueTransactionSetControlNumber != nil {
		toSerialize["requireUniqueTransactionSetControlNumber"] = o.RequireUniqueTransactionSetControlNumber
	}
	if o.RequireUniqueISAcontrolNumbersISA13 != nil {
		toSerialize["requireUniqueISAcontrolNumbersISA13"] = o.RequireUniqueISAcontrolNumbersISA13
	}
	if o.RequireUniqueGSControlNumbersGS06 != nil {
		toSerialize["requireUniqueGSControlNumbersGS06"] = o.RequireUniqueGSControlNumbersGS06
	}
	if o.RequireUniqueTransactionSetControlNumbersST02 != nil {
		toSerialize["requireUniqueTransactionSetControlNumbersST02"] = o.RequireUniqueTransactionSetControlNumbersST02
	}
	return json.Marshal(toSerialize)
}

type NullableEdiFormatConfigurationControlNumberSettings struct {
	value *EdiFormatConfigurationControlNumberSettings
	isSet bool
}

func (v NullableEdiFormatConfigurationControlNumberSettings) Get() *EdiFormatConfigurationControlNumberSettings {
	return v.value
}

func (v *NullableEdiFormatConfigurationControlNumberSettings) Set(val *EdiFormatConfigurationControlNumberSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableEdiFormatConfigurationControlNumberSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableEdiFormatConfigurationControlNumberSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEdiFormatConfigurationControlNumberSettings(val *EdiFormatConfigurationControlNumberSettings) *NullableEdiFormatConfigurationControlNumberSettings {
	return &NullableEdiFormatConfigurationControlNumberSettings{value: val, isSet: true}
}

func (v NullableEdiFormatConfigurationControlNumberSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEdiFormatConfigurationControlNumberSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


