/*
 * Partner Manager Partners API
 *
 * Anypoint Partner Manager - Partners API
 *
 * API version: v1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apm

import (
	"encoding/json"
)

// IdentifierTypeAllOf struct for IdentifierTypeAllOf
type IdentifierTypeAllOf struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Label string `json:"label"`
	Description string `json:"description"`
	Readonly *bool `json:"readonly,omitempty"`
	Qualifiers []IdentifierTypeQualifier `json:"qualifiers"`
	EnvironmentId *string `json:"environment_id,omitempty"`
}

// NewIdentifierTypeAllOf instantiates a new IdentifierTypeAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentifierTypeAllOf(id string, name string, label string, description string, qualifiers []IdentifierTypeQualifier) *IdentifierTypeAllOf {
	this := IdentifierTypeAllOf{}
	this.Id = id
	this.Name = name
	this.Label = label
	this.Description = description
	this.Qualifiers = qualifiers
	return &this
}

// NewIdentifierTypeAllOfWithDefaults instantiates a new IdentifierTypeAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentifierTypeAllOfWithDefaults() *IdentifierTypeAllOf {
	this := IdentifierTypeAllOf{}
	return &this
}

// GetId returns the Id field value
func (o *IdentifierTypeAllOf) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IdentifierTypeAllOf) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IdentifierTypeAllOf) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *IdentifierTypeAllOf) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *IdentifierTypeAllOf) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *IdentifierTypeAllOf) SetName(v string) {
	o.Name = v
}

// GetLabel returns the Label field value
func (o *IdentifierTypeAllOf) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *IdentifierTypeAllOf) GetLabelOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *IdentifierTypeAllOf) SetLabel(v string) {
	o.Label = v
}

// GetDescription returns the Description field value
func (o *IdentifierTypeAllOf) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *IdentifierTypeAllOf) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *IdentifierTypeAllOf) SetDescription(v string) {
	o.Description = v
}

// GetReadonly returns the Readonly field value if set, zero value otherwise.
func (o *IdentifierTypeAllOf) GetReadonly() bool {
	if o == nil || o.Readonly == nil {
		var ret bool
		return ret
	}
	return *o.Readonly
}

// GetReadonlyOk returns a tuple with the Readonly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifierTypeAllOf) GetReadonlyOk() (*bool, bool) {
	if o == nil || o.Readonly == nil {
		return nil, false
	}
	return o.Readonly, true
}

// HasReadonly returns a boolean if a field has been set.
func (o *IdentifierTypeAllOf) HasReadonly() bool {
	if o != nil && o.Readonly != nil {
		return true
	}

	return false
}

// SetReadonly gets a reference to the given bool and assigns it to the Readonly field.
func (o *IdentifierTypeAllOf) SetReadonly(v bool) {
	o.Readonly = &v
}

// GetQualifiers returns the Qualifiers field value
func (o *IdentifierTypeAllOf) GetQualifiers() []IdentifierTypeQualifier {
	if o == nil {
		var ret []IdentifierTypeQualifier
		return ret
	}

	return o.Qualifiers
}

// GetQualifiersOk returns a tuple with the Qualifiers field value
// and a boolean to check if the value has been set.
func (o *IdentifierTypeAllOf) GetQualifiersOk() (*[]IdentifierTypeQualifier, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Qualifiers, true
}

// SetQualifiers sets field value
func (o *IdentifierTypeAllOf) SetQualifiers(v []IdentifierTypeQualifier) {
	o.Qualifiers = v
}

// GetEnvironmentId returns the EnvironmentId field value if set, zero value otherwise.
func (o *IdentifierTypeAllOf) GetEnvironmentId() string {
	if o == nil || o.EnvironmentId == nil {
		var ret string
		return ret
	}
	return *o.EnvironmentId
}

// GetEnvironmentIdOk returns a tuple with the EnvironmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifierTypeAllOf) GetEnvironmentIdOk() (*string, bool) {
	if o == nil || o.EnvironmentId == nil {
		return nil, false
	}
	return o.EnvironmentId, true
}

// HasEnvironmentId returns a boolean if a field has been set.
func (o *IdentifierTypeAllOf) HasEnvironmentId() bool {
	if o != nil && o.EnvironmentId != nil {
		return true
	}

	return false
}

// SetEnvironmentId gets a reference to the given string and assigns it to the EnvironmentId field.
func (o *IdentifierTypeAllOf) SetEnvironmentId(v string) {
	o.EnvironmentId = &v
}

func (o IdentifierTypeAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["label"] = o.Label
	}
	if true {
		toSerialize["description"] = o.Description
	}
	if o.Readonly != nil {
		toSerialize["readonly"] = o.Readonly
	}
	if true {
		toSerialize["qualifiers"] = o.Qualifiers
	}
	if o.EnvironmentId != nil {
		toSerialize["environment_id"] = o.EnvironmentId
	}
	return json.Marshal(toSerialize)
}

type NullableIdentifierTypeAllOf struct {
	value *IdentifierTypeAllOf
	isSet bool
}

func (v NullableIdentifierTypeAllOf) Get() *IdentifierTypeAllOf {
	return v.value
}

func (v *NullableIdentifierTypeAllOf) Set(val *IdentifierTypeAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentifierTypeAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentifierTypeAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentifierTypeAllOf(val *IdentifierTypeAllOf) *NullableIdentifierTypeAllOf {
	return &NullableIdentifierTypeAllOf{value: val, isSet: true}
}

func (v NullableIdentifierTypeAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentifierTypeAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


