/*
 * Partner Manager Partners API
 *
 * Anypoint Partner Manager - Partners API
 *
 * API version: v1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apm

import (
	"encoding/json"
)

// DocumentFlowDeploymentSummaryAllOf struct for DocumentFlowDeploymentSummaryAllOf
type DocumentFlowDeploymentSummaryAllOf struct {
	Id *string `json:"id,omitempty"`
	EnvironmentId *string `json:"environmentId,omitempty"`
	EnvironmentName *string `json:"environmentName,omitempty"`
	DocumentsProcessed *float32 `json:"documentsProcessed,omitempty"`
}

// NewDocumentFlowDeploymentSummaryAllOf instantiates a new DocumentFlowDeploymentSummaryAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentFlowDeploymentSummaryAllOf() *DocumentFlowDeploymentSummaryAllOf {
	this := DocumentFlowDeploymentSummaryAllOf{}
	var documentsProcessed float32 = 0
	this.DocumentsProcessed = &documentsProcessed
	return &this
}

// NewDocumentFlowDeploymentSummaryAllOfWithDefaults instantiates a new DocumentFlowDeploymentSummaryAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentFlowDeploymentSummaryAllOfWithDefaults() *DocumentFlowDeploymentSummaryAllOf {
	this := DocumentFlowDeploymentSummaryAllOf{}
	var documentsProcessed float32 = 0
	this.DocumentsProcessed = &documentsProcessed
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DocumentFlowDeploymentSummaryAllOf) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentFlowDeploymentSummaryAllOf) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DocumentFlowDeploymentSummaryAllOf) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DocumentFlowDeploymentSummaryAllOf) SetId(v string) {
	o.Id = &v
}

// GetEnvironmentId returns the EnvironmentId field value if set, zero value otherwise.
func (o *DocumentFlowDeploymentSummaryAllOf) GetEnvironmentId() string {
	if o == nil || o.EnvironmentId == nil {
		var ret string
		return ret
	}
	return *o.EnvironmentId
}

// GetEnvironmentIdOk returns a tuple with the EnvironmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentFlowDeploymentSummaryAllOf) GetEnvironmentIdOk() (*string, bool) {
	if o == nil || o.EnvironmentId == nil {
		return nil, false
	}
	return o.EnvironmentId, true
}

// HasEnvironmentId returns a boolean if a field has been set.
func (o *DocumentFlowDeploymentSummaryAllOf) HasEnvironmentId() bool {
	if o != nil && o.EnvironmentId != nil {
		return true
	}

	return false
}

// SetEnvironmentId gets a reference to the given string and assigns it to the EnvironmentId field.
func (o *DocumentFlowDeploymentSummaryAllOf) SetEnvironmentId(v string) {
	o.EnvironmentId = &v
}

// GetEnvironmentName returns the EnvironmentName field value if set, zero value otherwise.
func (o *DocumentFlowDeploymentSummaryAllOf) GetEnvironmentName() string {
	if o == nil || o.EnvironmentName == nil {
		var ret string
		return ret
	}
	return *o.EnvironmentName
}

// GetEnvironmentNameOk returns a tuple with the EnvironmentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentFlowDeploymentSummaryAllOf) GetEnvironmentNameOk() (*string, bool) {
	if o == nil || o.EnvironmentName == nil {
		return nil, false
	}
	return o.EnvironmentName, true
}

// HasEnvironmentName returns a boolean if a field has been set.
func (o *DocumentFlowDeploymentSummaryAllOf) HasEnvironmentName() bool {
	if o != nil && o.EnvironmentName != nil {
		return true
	}

	return false
}

// SetEnvironmentName gets a reference to the given string and assigns it to the EnvironmentName field.
func (o *DocumentFlowDeploymentSummaryAllOf) SetEnvironmentName(v string) {
	o.EnvironmentName = &v
}

// GetDocumentsProcessed returns the DocumentsProcessed field value if set, zero value otherwise.
func (o *DocumentFlowDeploymentSummaryAllOf) GetDocumentsProcessed() float32 {
	if o == nil || o.DocumentsProcessed == nil {
		var ret float32
		return ret
	}
	return *o.DocumentsProcessed
}

// GetDocumentsProcessedOk returns a tuple with the DocumentsProcessed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentFlowDeploymentSummaryAllOf) GetDocumentsProcessedOk() (*float32, bool) {
	if o == nil || o.DocumentsProcessed == nil {
		return nil, false
	}
	return o.DocumentsProcessed, true
}

// HasDocumentsProcessed returns a boolean if a field has been set.
func (o *DocumentFlowDeploymentSummaryAllOf) HasDocumentsProcessed() bool {
	if o != nil && o.DocumentsProcessed != nil {
		return true
	}

	return false
}

// SetDocumentsProcessed gets a reference to the given float32 and assigns it to the DocumentsProcessed field.
func (o *DocumentFlowDeploymentSummaryAllOf) SetDocumentsProcessed(v float32) {
	o.DocumentsProcessed = &v
}

func (o DocumentFlowDeploymentSummaryAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.EnvironmentId != nil {
		toSerialize["environmentId"] = o.EnvironmentId
	}
	if o.EnvironmentName != nil {
		toSerialize["environmentName"] = o.EnvironmentName
	}
	if o.DocumentsProcessed != nil {
		toSerialize["documentsProcessed"] = o.DocumentsProcessed
	}
	return json.Marshal(toSerialize)
}

type NullableDocumentFlowDeploymentSummaryAllOf struct {
	value *DocumentFlowDeploymentSummaryAllOf
	isSet bool
}

func (v NullableDocumentFlowDeploymentSummaryAllOf) Get() *DocumentFlowDeploymentSummaryAllOf {
	return v.value
}

func (v *NullableDocumentFlowDeploymentSummaryAllOf) Set(val *DocumentFlowDeploymentSummaryAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentFlowDeploymentSummaryAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentFlowDeploymentSummaryAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentFlowDeploymentSummaryAllOf(val *DocumentFlowDeploymentSummaryAllOf) *NullableDocumentFlowDeploymentSummaryAllOf {
	return &NullableDocumentFlowDeploymentSummaryAllOf{value: val, isSet: true}
}

func (v NullableDocumentFlowDeploymentSummaryAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentFlowDeploymentSummaryAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


