/*
 * Partner Manager Partners API
 *
 * Anypoint Partner Manager - Partners API
 *
 * API version: v1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apm

import (
	"encoding/json"
	"time"
)

// DocumentFlowAllOf struct for DocumentFlowAllOf
type DocumentFlowAllOf struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Direction *string `json:"direction,omitempty"`
	PartnerFromId *string `json:"partnerFromId,omitempty"`
	PartnerToId *string `json:"partnerToId,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	CreatedBy *string `json:"createdBy,omitempty"`
	ModifierAt *time.Time `json:"modifierAt,omitempty"`
	ModifiedBy *string `json:"modifiedBy,omitempty"`
	Configurations *[]DocumentFlowConfig `json:"configurations,omitempty"`
}

// NewDocumentFlowAllOf instantiates a new DocumentFlowAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentFlowAllOf() *DocumentFlowAllOf {
	this := DocumentFlowAllOf{}
	return &this
}

// NewDocumentFlowAllOfWithDefaults instantiates a new DocumentFlowAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentFlowAllOfWithDefaults() *DocumentFlowAllOf {
	this := DocumentFlowAllOf{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DocumentFlowAllOf) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentFlowAllOf) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DocumentFlowAllOf) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DocumentFlowAllOf) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DocumentFlowAllOf) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentFlowAllOf) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DocumentFlowAllOf) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DocumentFlowAllOf) SetName(v string) {
	o.Name = &v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *DocumentFlowAllOf) GetDirection() string {
	if o == nil || o.Direction == nil {
		var ret string
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentFlowAllOf) GetDirectionOk() (*string, bool) {
	if o == nil || o.Direction == nil {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *DocumentFlowAllOf) HasDirection() bool {
	if o != nil && o.Direction != nil {
		return true
	}

	return false
}

// SetDirection gets a reference to the given string and assigns it to the Direction field.
func (o *DocumentFlowAllOf) SetDirection(v string) {
	o.Direction = &v
}

// GetPartnerFromId returns the PartnerFromId field value if set, zero value otherwise.
func (o *DocumentFlowAllOf) GetPartnerFromId() string {
	if o == nil || o.PartnerFromId == nil {
		var ret string
		return ret
	}
	return *o.PartnerFromId
}

// GetPartnerFromIdOk returns a tuple with the PartnerFromId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentFlowAllOf) GetPartnerFromIdOk() (*string, bool) {
	if o == nil || o.PartnerFromId == nil {
		return nil, false
	}
	return o.PartnerFromId, true
}

// HasPartnerFromId returns a boolean if a field has been set.
func (o *DocumentFlowAllOf) HasPartnerFromId() bool {
	if o != nil && o.PartnerFromId != nil {
		return true
	}

	return false
}

// SetPartnerFromId gets a reference to the given string and assigns it to the PartnerFromId field.
func (o *DocumentFlowAllOf) SetPartnerFromId(v string) {
	o.PartnerFromId = &v
}

// GetPartnerToId returns the PartnerToId field value if set, zero value otherwise.
func (o *DocumentFlowAllOf) GetPartnerToId() string {
	if o == nil || o.PartnerToId == nil {
		var ret string
		return ret
	}
	return *o.PartnerToId
}

// GetPartnerToIdOk returns a tuple with the PartnerToId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentFlowAllOf) GetPartnerToIdOk() (*string, bool) {
	if o == nil || o.PartnerToId == nil {
		return nil, false
	}
	return o.PartnerToId, true
}

// HasPartnerToId returns a boolean if a field has been set.
func (o *DocumentFlowAllOf) HasPartnerToId() bool {
	if o != nil && o.PartnerToId != nil {
		return true
	}

	return false
}

// SetPartnerToId gets a reference to the given string and assigns it to the PartnerToId field.
func (o *DocumentFlowAllOf) SetPartnerToId(v string) {
	o.PartnerToId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DocumentFlowAllOf) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentFlowAllOf) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DocumentFlowAllOf) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *DocumentFlowAllOf) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *DocumentFlowAllOf) GetCreatedBy() string {
	if o == nil || o.CreatedBy == nil {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentFlowAllOf) GetCreatedByOk() (*string, bool) {
	if o == nil || o.CreatedBy == nil {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *DocumentFlowAllOf) HasCreatedBy() bool {
	if o != nil && o.CreatedBy != nil {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *DocumentFlowAllOf) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetModifierAt returns the ModifierAt field value if set, zero value otherwise.
func (o *DocumentFlowAllOf) GetModifierAt() time.Time {
	if o == nil || o.ModifierAt == nil {
		var ret time.Time
		return ret
	}
	return *o.ModifierAt
}

// GetModifierAtOk returns a tuple with the ModifierAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentFlowAllOf) GetModifierAtOk() (*time.Time, bool) {
	if o == nil || o.ModifierAt == nil {
		return nil, false
	}
	return o.ModifierAt, true
}

// HasModifierAt returns a boolean if a field has been set.
func (o *DocumentFlowAllOf) HasModifierAt() bool {
	if o != nil && o.ModifierAt != nil {
		return true
	}

	return false
}

// SetModifierAt gets a reference to the given time.Time and assigns it to the ModifierAt field.
func (o *DocumentFlowAllOf) SetModifierAt(v time.Time) {
	o.ModifierAt = &v
}

// GetModifiedBy returns the ModifiedBy field value if set, zero value otherwise.
func (o *DocumentFlowAllOf) GetModifiedBy() string {
	if o == nil || o.ModifiedBy == nil {
		var ret string
		return ret
	}
	return *o.ModifiedBy
}

// GetModifiedByOk returns a tuple with the ModifiedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentFlowAllOf) GetModifiedByOk() (*string, bool) {
	if o == nil || o.ModifiedBy == nil {
		return nil, false
	}
	return o.ModifiedBy, true
}

// HasModifiedBy returns a boolean if a field has been set.
func (o *DocumentFlowAllOf) HasModifiedBy() bool {
	if o != nil && o.ModifiedBy != nil {
		return true
	}

	return false
}

// SetModifiedBy gets a reference to the given string and assigns it to the ModifiedBy field.
func (o *DocumentFlowAllOf) SetModifiedBy(v string) {
	o.ModifiedBy = &v
}

// GetConfigurations returns the Configurations field value if set, zero value otherwise.
func (o *DocumentFlowAllOf) GetConfigurations() []DocumentFlowConfig {
	if o == nil || o.Configurations == nil {
		var ret []DocumentFlowConfig
		return ret
	}
	return *o.Configurations
}

// GetConfigurationsOk returns a tuple with the Configurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentFlowAllOf) GetConfigurationsOk() (*[]DocumentFlowConfig, bool) {
	if o == nil || o.Configurations == nil {
		return nil, false
	}
	return o.Configurations, true
}

// HasConfigurations returns a boolean if a field has been set.
func (o *DocumentFlowAllOf) HasConfigurations() bool {
	if o != nil && o.Configurations != nil {
		return true
	}

	return false
}

// SetConfigurations gets a reference to the given []DocumentFlowConfig and assigns it to the Configurations field.
func (o *DocumentFlowAllOf) SetConfigurations(v []DocumentFlowConfig) {
	o.Configurations = &v
}

func (o DocumentFlowAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Direction != nil {
		toSerialize["direction"] = o.Direction
	}
	if o.PartnerFromId != nil {
		toSerialize["partnerFromId"] = o.PartnerFromId
	}
	if o.PartnerToId != nil {
		toSerialize["partnerToId"] = o.PartnerToId
	}
	if o.CreatedAt != nil {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.CreatedBy != nil {
		toSerialize["createdBy"] = o.CreatedBy
	}
	if o.ModifierAt != nil {
		toSerialize["modifierAt"] = o.ModifierAt
	}
	if o.ModifiedBy != nil {
		toSerialize["modifiedBy"] = o.ModifiedBy
	}
	if o.Configurations != nil {
		toSerialize["configurations"] = o.Configurations
	}
	return json.Marshal(toSerialize)
}

type NullableDocumentFlowAllOf struct {
	value *DocumentFlowAllOf
	isSet bool
}

func (v NullableDocumentFlowAllOf) Get() *DocumentFlowAllOf {
	return v.value
}

func (v *NullableDocumentFlowAllOf) Set(val *DocumentFlowAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentFlowAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentFlowAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentFlowAllOf(val *DocumentFlowAllOf) *NullableDocumentFlowAllOf {
	return &NullableDocumentFlowAllOf{value: val, isSet: true}
}

func (v NullableDocumentFlowAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentFlowAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


