/*
 * Partner Manager Partners API
 *
 * Anypoint Partner Manager - Partners API
 *
 * API version: v1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apm

import (
	"encoding/json"
)

// AuthModeBasicAllOf struct for AuthModeBasicAllOf
type AuthModeBasicAllOf struct {
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
}

// NewAuthModeBasicAllOf instantiates a new AuthModeBasicAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthModeBasicAllOf() *AuthModeBasicAllOf {
	this := AuthModeBasicAllOf{}
	return &this
}

// NewAuthModeBasicAllOfWithDefaults instantiates a new AuthModeBasicAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthModeBasicAllOfWithDefaults() *AuthModeBasicAllOf {
	this := AuthModeBasicAllOf{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *AuthModeBasicAllOf) GetUsername() string {
	if o == nil || o.Username == nil {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthModeBasicAllOf) GetUsernameOk() (*string, bool) {
	if o == nil || o.Username == nil {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *AuthModeBasicAllOf) HasUsername() bool {
	if o != nil && o.Username != nil {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *AuthModeBasicAllOf) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *AuthModeBasicAllOf) GetPassword() string {
	if o == nil || o.Password == nil {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthModeBasicAllOf) GetPasswordOk() (*string, bool) {
	if o == nil || o.Password == nil {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *AuthModeBasicAllOf) HasPassword() bool {
	if o != nil && o.Password != nil {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *AuthModeBasicAllOf) SetPassword(v string) {
	o.Password = &v
}

func (o AuthModeBasicAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Username != nil {
		toSerialize["username"] = o.Username
	}
	if o.Password != nil {
		toSerialize["password"] = o.Password
	}
	return json.Marshal(toSerialize)
}

type NullableAuthModeBasicAllOf struct {
	value *AuthModeBasicAllOf
	isSet bool
}

func (v NullableAuthModeBasicAllOf) Get() *AuthModeBasicAllOf {
	return v.value
}

func (v *NullableAuthModeBasicAllOf) Set(val *AuthModeBasicAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthModeBasicAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthModeBasicAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthModeBasicAllOf(val *AuthModeBasicAllOf) *NullableAuthModeBasicAllOf {
	return &NullableAuthModeBasicAllOf{value: val, isSet: true}
}

func (v NullableAuthModeBasicAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthModeBasicAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


