name: Go Client Generator

on:
  push:
    branches:
      - master

jobs:
  create-tag:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with: 
          ref: 'master'
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set Version Number based on Date and build number
        if: ${{ !inputs.test-only }}
        id: version
        run: |
          PATCH+=$(date +'%Y%m%d')
          PATCH+=${{ github.run_number }}
          echo VERSION_OUTPUT=1.0.$PATCH >> $GITHUB_OUTPUT

      - name: Retrieve tag exists flag
        uses: mukunku/tag-exists-action@v1.4.0
        id: checkTag
        with:
          tag: ${{ steps.version.outputs.VERSION_OUTPUT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify and create tag if not exists
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        uses: mathieudutour/github-tag-action@v6.1
        with:
          default_bump: false
          custom_tag: ${{ steps.version.outputs.VERSION_OUTPUT }}
          tag_prefix: "v"
          github_token: ${{ secrets.GITHUB_TOKEN }}