name: Mule Pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push
  push:
    branches: [ dev ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate_code:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ~/workspace
    strategy:
      matrix:
        node-version: [14.x]
    env:
      CLIENT_GO_REPO_NAME: mulesoft-consulting/cloudhub-client-go
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare Bash env variables and workspace
        run: |
          > ~/.bashrc
          echo 'export GENERATOR_FOLDER="~/workspace/cloudhub-client-generator"' >> ~/.bashrc
          echo 'export GO_CLIENT_FOLDER="~/workspace/cloudhub-client-generator"' >> ~/.bashrc
          echo 'export GOPATH="$GO_CLIENT_FOLDER"' >> ~/.bashrc
          source ~/.bashrc
          mkdir -p $GENERATOR_FOLDER
          mkdir -p $GO_CLIENT_FOLDER

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Copy Cloudhub-client-generator project
        run: |
          source ~/.bashrc
          cp -r ./. $GENERATOR_FOLDER/
          cd $GENERATOR_FOLDER
          npm install
      
      - name: List copy
        run: |
          source ~/.bashrc
          cd $GENERATOR_FOLDER
          pwd
          ls -al

      - name: Clone destination repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.CLIENT_GO_REPO_NAME }}
          ref: refs/heads/dev
          token: ${{ env.GIT_TOKEN }}

      - name: Prepare destination repo
        run: |
          source ~/.bashrc
          cp -r ./. $GO_CLIENT_FOLDER



